Italian Translations - Chapter 2
microsoft/ML-For-Beginners pull request #204
Opened 2021-07-18 14:21 UTC by robertopauletto

https://github.com/microsoft/ML-For-Beginners/tree/main/2-Regression/2-Data

Sentence:

"To get charts to display useful data, you usually need to group the data somehow.
Let's try creating a plot where the y axis shows the months and the data demonstrates
the distribution of data"

I am confused, should the months be on the x-axis and what does it mean "the data demonstrates
the distribution of data"?

2021-07-18 14:25 UTC, jlooper commented
> https://github.com/microsoft/ML-For-Beginners/tree/main/2-Regression/2-Data
> 
> Sentence:
> 
> "To get charts to display useful data, you usually need to group the data somehow.
> Let's try creating a plot where the y axis shows the months and the data demonstrates
> the distribution of data"
> 
> I am confused, should the months be on the x-axis and what does it mean "the data demonstrates
> the distribution of data"?

good catch! It should be:

Let's try creating a plot where the x axis shows the months and the chart illustrates the distribution of data

2021-07-18 14:26 UTC, jlooper requested changes

2021-07-18 14:26 UTC, jlooper commented on 2-Regression/translations/README.it.md
> +1. [Gli Attrezzi Necessari](1-Tools/README.md)
I think you can link to the translations here, right?

2021-07-18 17:42 UTC, robertopauletto commented
Sentence modified.

Thanks!

2021-07-19 00:19 UTC, jlooper approved these changes

2021-07-19 00:19 UTC, merged