2-Regression/1-Tools/translations/assignment.es.md
microsoft/ML-For-Beginners pull request #296
Opened 2021-08-14 22:22 UTC by davidit33

2021-08-16 14:49 UTC, alfredodeza requested changes

2021-08-16 14:49 UTC, alfredodeza commented on 2-Regression/1-Tools/translations/assignment.es.md
> +En tus palabras, describa como crear un modelo de regresión que trazaría la relación entre la cintura y la cantidad de abdominales que se realizan. Haga lo mismo con otros puntos de datos en el _data
This should be either:

> En sus palabras, describa

Or:

> En tus palabras, describe

2021-08-16 19:08 UTC, davidit33 commented on 2-Regression/1-Tools/translations/assignment.es.md
> +En tus palabras, describa como crear un modelo de regresión que trazaría la relación entre la cintura y la cantidad de abdominales que se realizan. Haga lo mismo con otros puntos de datos en el _data
Yes, Thanks!

2021-08-17 12:40 UTC, alfredodeza approved these changes

2021-08-17 12:40 UTC, merged