ufo-model.pkl file should be in the same directory as app.py
microsoft/ML-For-Beginners pull request #469
Opened 2021-11-19 22:14 UTC by ayyucedemirbas

ufo-model.pkl model file should be in the same directory as app.py file

2021-11-19 22:46 UTC, jlooper requested changes
hi, could you check the text lesson and all translations to make this edit as well? thanks

2021-11-20 15:20 UTC, ayyucedemirbas commented
Thank you so much! I've fixed the problem for all the translations, please check the pull requests

2021-11-20 18:39 UTC, jlooper commented
hi, let me close this one and merge the other - normally you can just edit a current PR for requested changes, thanks

2021-11-21 16:06 UTC, jlooper approved these changes

2021-11-21 16:06 UTC, merged