(spanish) 8-Reinforcement/2-Gym/assignment.md
microsoft/ML-For-Beginners pull request #537
Opened 2022-02-21 04:57 UTC by hereje

Translate file `8-Reinforcement/2-Gym/assignment.md` to spanish

2022-02-23 18:39 UTC, Stevengez requested changes
Great job with the translation!, I added some suggestions to make it even better

2022-02-23 18:39 UTC, Stevengez commented on 8-Reinforcement/2-Gym/translations/assignment.es.md
> +El truco principal de este problema es, no obstante, que el motor del carrito no es lo suficientemente potente para escalar la montaña en una sola pasada. Por lo tanto, la única forma de lograrlo es
```suggestion
El truco principal de este problema es, no obstante, que el motor del carrito no es lo suficientemente potente para escalar la montaña en una sola pasada. Por lo tanto, la única forma de lograrlo es conducir hacia atrás y adelante para generar impulso.
```

2022-02-23 18:39 UTC, Stevengez commented on 8-Reinforcement/2-Gym/translations/assignment.es.md
> +El sistema de recompensas para el carrito de montaña es bastante difícil:
```suggestion
El sistema de recompensas para el carrito de montaña es engañoso:
```

2022-02-23 18:39 UTC, Stevengez commented on 8-Reinforcement/2-Gym/translations/assignment.es.md
> +* La recompensa de 0 es otorgada si el agente alcanzó la bandera (position = 0.5) en la cima de la montaña.
```suggestion
* La recompensa de 0 es otorgada si el agente alcanzó la bandera (posición = 0.5) en la cima de la montaña.
```

2022-02-23 18:39 UTC, Stevengez commented on 8-Reinforcement/2-Gym/translations/assignment.es.md
> +> **Nota**: El ajuste de los hiperparámetros es probable sea necesario para hacer que el algoritmo converja.
```suggestion
> **Nota**: Es probable que ajustar los hiperparámetros sea necesario para hacer que el algoritmo converja.
```

2022-02-23 18:39 UTC, Stevengez commented on 8-Reinforcement/2-Gym/translations/assignment.es.md
> +|          | El algoritmo Q-Learning se adaptó de forma exitosa a partir del ejemplo CartPole, con mínimas modificaciones al código, el cual es capaz de resolver el problema al capturar la bandera co
```suggestion
|          | El algoritmo Q-Learning se adaptó de forma exitosa a partir del ejemplo CartPole, con mínimas modificaciones al código, el cual es capaz de resolver el problema al capturar la bandera con menos de 200 pasos. | Se adoptó un nuevo algoritmo Q-Learning de internet, pero está bien documentado; o se adoptó el algoritmo existente, pero no cumple los resultados deseados | El estudiante no fue capaz de adoptar ningun algoritmo de forma exitosa, pero ha hecho pasos substanciales hacia la solución (implementó la discretización de estado, la estructura de datos de Q-Table, etc.) |
```

2022-02-24 16:07 UTC, jlooper commented
thank you for the review!

2022-02-24 16:07 UTC, merged