(spanish) README.md
microsoft/ML-For-Beginners pull request #538
Opened 2022-02-22 06:19 UTC by hereje

Translate file `README.md` to spanish

NOTE: This PR must be merged when the whole translation is completed, so that the links work properly.

2022-02-23 18:10 UTC, Stevengez requested changes
Great translate overall, I added some suggestion to make it even better

2022-02-23 18:10 UTC, Stevengez commented on translations/README.es.md
> +> **Una nota acerca de los exámenes**: Todos los exámenes están contenidos [en esta app](https://white-water-09ec41f0f.azurestaticapps.net/), por un total de 52 exámenes de 3 preguntas cada uno, Ello
```suggestion
> **Una nota acerca de los exámenes**: Todos los exámenes están contenidos [en esta app](https://white-water-09ec41f0f.azurestaticapps.net/), para un total de 52 exámenes de 3 preguntas cada uno, Ellos están vinculados dentro de las lecciones pero la aplicación de exámenes puede ser ejecutada localmente; sigue las instrucciones en el directorio `quiz-app`.
```

2022-02-23 22:07 UTC, abrildur reviewed
¡Hola! Hice algunas modificaciones a las traducciones originales, espero que les sea útil :D

2022-02-23 22:48 UTC, hereje commented on translations/README.es.md
Done!

2022-02-23 22:48 UTC, hereje commented on translations/README.es.md
Done!

2022-02-23 22:48 UTC, hereje commented
@abrildur , gracias por el aporte.

2022-03-08 16:14 UTC, jlooper approved these changes

2022-03-08 16:14 UTC, merged